include "/etc/bind/named.conf.options";
include "/etc/bind/named.conf.default-zones";

zone "lab.myviewsontech.local" {
    type master;
    file "/etc/bind/zones/lab.myviewsontech.local.zone";
};

zone "10.168.192.in-addr.arpa" {
    type master;
    file "/etc/bind/zones/reverse.zone";
};
