options {
    directory "/var/cache/bind";
    recursion no;
    allow-query { any; };
};

zone "lab.myviewsontech.local" {
    type master;
    file "/etc/bind/zones/lab.myviewsontech.local.zone";
};

zone "10.168.192.in-addr.arpa" {
    type master;
    file "/etc/bind/zones/reverse.zone";
};
